/**
 * 
 */
package com.github.miniminelp.mcscript.java.filemanager;

import com.github.miniminelp.mcscript.java.util.MCScriptObject;

/**
 * @author Minimine
 * @since 0.0.1
 * @version 0.0.1
 *
 */
public class OutFile implements MCScriptObject {
	
	protected String filename;
	protected String content; 

	/**
	 * @param filename Filename of outfile
	 */
	public OutFile(String filename) {
		setFilename(filename);
		content = "#######" + LINESEPERATOR  
				+ "# File: ./"+filename + LINESEPERATOR
				+ "#" + LINESEPERATOR
				+ "# Generated by Minecraft Script for 1.13" + LINESEPERATOR 
				+ "######" + LINESEPERATOR + LINESEPERATOR;
	}
	
	
	
	/**
	 * @param cmd command to add {@link String}
	 */
	public void write (String cmd) {
		
		cmd = cmd.replaceAll("\r", "")
				 .replaceAll("\n", "")
				 .replaceAll("\r\n", "")
				 .replaceAll("\t", "")
				 .replaceAll("	", "");
		
		while(cmd.contains(LINESEPERATOR+LINESEPERATOR))
			cmd = cmd.replaceAll(LINESEPERATOR+LINESEPERATOR, LINESEPERATOR);
		
		content +=  cmd + LINESEPERATOR;
		
	}
	
	/**
	 * @return The load content {@link String}
	 */
	public String getContent () {
		
		return content;
		
	}

	/**
	 * @param content the content to set {@link String}
	 */
	public void setContent(String content) {
		
		this.content=content;
		
	}
	
	/**
	 * @return the filename
	 */
	public String getFilename() {
		return filename;
	}
	
	/**
	 * @param filename the filename to set
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}
}
